services:
  shop_postgres:
    container_name: shop_postgres
    image: postgres:13.3
    environment:
      - POSTGRES_USER=Marco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=feed_rank
    ports:
      - '5444:5444'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  shop_redis:
    container_name: shop_redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
