spring:
  application:
    name: SmartFeedRanking

  datasource:
    url: jdbc:postgresql://172.17.0.1:5444/feed_rank
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6333
      database: 0

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  banner:
    location: banner/banner-dev.txt

springdoc:
  swagger-ui:
    path: /docs
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

minio:
  url: http://localhost:9000
  access-key: Marco
  secret-key: 1234
  bucket-name: google-shop-bucket